### ISSUE TITLE
Problem with start locally docker-compose

### ISSUE THREAD

**Issue by ddovnar** [OpenLMIS/openlmis-ref-distro#134]
I'm trying to start docker compose. All services starts normally, but when I go to the browser and enter login with password, I've got an error "Timeout", the information in the log:
```
openlmis-ref-distro-referencedata-1          | org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://192.168.0.107/api/oauth/check_token": Operation timed out (Connection timed out); nested exception is java.net.ConnectException: Operation timed out (Connection timed out)
openlmis-ref-distro-referencedata-1          |   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:751)
openlmis-ref-distro-referencedata-1          |   at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677)
openlmis-ref-distro-referencedata-1          |   at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:586)
openlmis-ref-distro-referencedata-1          |   at org.springframework.security.oauth2.provider.token.RemoteTokenServices.postForMap(RemoteTokenServices.java:149)
openlmis-ref-distro-referencedata-1          |   at org.springframework.security.oauth2.provider.token.RemoteTokenServices.loadAuthentication(RemoteTokenServices.java:106)
openlmis-ref-distro-referencedata-1          |   at org.openlmis.referencedata.security.CustomTokenServices.loadAuthentication(CustomTokenServices.java:38)
openlmis-ref-distro-referencedata-1          |   at org.openlmis.referencedata.security.CustomTokenServices.loadAuthentication(CustomTokenServices.java:33)
```

**Comment by ddovnar** [comment]
![image](https://github.com/OpenLMIS/openlmis-ref-distro/assets/39269414/bae2cd77-7d21-42ec-a8f3-17368a015baf)
